[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SIMDIntrinsics = "35fb604a-ffdf-11e8-0d1a-af07cb8bab46"

[compat]
Documenter = "0.23"
Literate = "2"
